export interface DaySchedule {
  schSeq: number;
  dates: Date;
  schTitle: string;
  isAllday: boolean;
  serviceTypeSeq: number;
  serviceTypeName: string;
  startTime: string;
  endTime: string;
  viewColor: string;
}
export const daySchedules: DaySchedule[] = [
  {
    schSeq: 1,
    schTitle: "야간 순찰(동 A·B)",
    dates: new Date("2025-08-03"),
    isAllday: true,
    serviceTypeSeq: 31,
    serviceTypeName: "보안",
    startTime: "00:00",
    endTime: "23:59",
    viewColor: "1e90ff",
  },
  {
    schSeq: 2,
    schTitle: "로비 유리창 정기 세척",
    dates: new Date("2025-08-07"),
    isAllday: false,
    serviceTypeSeq: 32,
    serviceTypeName: "미화",
    startTime: "09:00",
    endTime: "11:30",
    viewColor: "2ecc71",
  },
  {
    schSeq: 3,
    schTitle: "전기실 분전반 점검",
    dates: new Date("2025-08-15"),
    isAllday: false,
    serviceTypeSeq: 33,
    serviceTypeName: "설비",
    startTime: "13:30",
    endTime: "16:00",
    viewColor: "e67e22",
  },
  {
    schSeq: 4,
    schTitle: "공용부 월간 대청소",
    dates: new Date("2025-08-22"),
    isAllday: true,
    serviceTypeSeq: 32,
    serviceTypeName: "미화",
    startTime: "00:00",
    endTime: "23:59",
    viewColor: "2ecc71",
  },
  {
    schSeq: 5,
    schTitle: "출입권한 점검/갱신",
    dates: new Date("2025-08-29"),
    isAllday: false,
    serviceTypeSeq: 31,
    serviceTypeName: "보안",
    startTime: "20:00",
    endTime: "23:00",
    viewColor: "1e90ff",
  },
  {
    schSeq: 6,
    schTitle: "냉각탑 점검 및 세척",
    dates: new Date("2025-09-02"),
    isAllday: false,
    serviceTypeSeq: 33,
    serviceTypeName: "설비",
    startTime: "08:00",
    endTime: "12:00",
    viewColor: "e67e22",
  },
  {
    schSeq: 7,
    schTitle: "비상대응 모의훈련",
    dates: new Date("2025-09-10"),
    isAllday: true,
    serviceTypeSeq: 31,
    serviceTypeName: "보안",
    startTime: "00:00",
    endTime: "23:59",
    viewColor: "1e90ff",
  },
  {
    schSeq: 12,
    schTitle: "비상대응 모의훈련2",
    dates: new Date("2025-09-10"),
    isAllday: true,
    serviceTypeSeq: 31,
    serviceTypeName: "보안",
    startTime: "00:00",
    endTime: "23:59",
    viewColor: "1e90ff",
  },
  {
    schSeq: 8,
    schTitle: "카펫 스팀세척(3F)",
    dates: new Date("2025-09-14"),
    isAllday: false,
    serviceTypeSeq: 32,
    serviceTypeName: "미화",
    startTime: "14:00",
    endTime: "17:00",
    viewColor: "2ecc71",
  },
  {
    schSeq: 9,
    schTitle: "UPS 배터리 상태 점검",
    dates: new Date("2025-09-21"),
    isAllday: false,
    serviceTypeSeq: 33,
    serviceTypeName: "설비",
    startTime: "10:00",
    endTime: "12:00",
    viewColor: "e67e22",
  },
  {
    schSeq: 10,
    schTitle: "화장실 소독(전층)",
    dates: new Date("2025-09-28"),
    isAllday: true,
    serviceTypeSeq: 32,
    serviceTypeName: "미화",
    startTime: "00:00",
    endTime: "23:59",
    viewColor: "2ecc71",
  },
  {
    schSeq: 11,
    schTitle: "화장실 소독(전층)2",
    dates: new Date("2025-09-28"),
    isAllday: true,
    serviceTypeSeq: 32,
    serviceTypeName: "미화",
    startTime: "00:00",
    endTime: "23:59",
    viewColor: "2ecc71",
  },
];
