export interface MonthScheduleListItem {
  planSeq: number;
  serviceTypeSeq: number;
  serviceTypeName: string;
  planTitle: string;
  description: string | null;
  planDt: Date;
}

export const monthSchedules: MonthScheduleListItem[] = [
  {
    planSeq: 1,
    serviceTypeSeq: 31,
    serviceTypeName: "보안",
    planTitle: "야간 순찰 강화",
    description: "설명",
    planDt: new Date("2025-08-01"),
  },
  {
    planSeq: 40,
    serviceTypeSeq: 31,
    serviceTypeName: "보안",
    planTitle: "야간 순찰 강화11",
    description: "설명",
    planDt: new Date("2025-08-01"),
  },
  {
    planSeq: 2,
    serviceTypeSeq: 32,
    serviceTypeName: "미화",
    planTitle: "로비 유리창 정기 세척",
    description: "설명",
    planDt: new Date("2025-08-02"),
  },
  {
    planSeq: 3,
    serviceTypeSeq: 33,
    serviceTypeName: "설비",
    planTitle: "전기실 점검(분전반)",
    description: "설명",
    planDt: new Date("2025-08-03"),
  },
  {
    planSeq: 4,
    serviceTypeSeq: 31,
    serviceTypeName: "보안",
    planTitle: "출입권한 월간 점검",
    description: "설명",
    planDt: new Date("2025-08-04"),
  },
  {
    planSeq: 5,
    serviceTypeSeq: 32,
    serviceTypeName: "미화",
    planTitle: "지하주차장 바닥 세척",
    description: "설명",
    planDt: new Date("2025-08-05"),
  },
  {
    planSeq: 6,
    serviceTypeSeq: 33,
    serviceTypeName: "설비",
    planTitle: "냉각탑 점검/세척",
    description: "설명",
    planDt: new Date("2025-08-06"),
  },
  {
    planSeq: 7,
    serviceTypeSeq: 31,
    serviceTypeName: "보안",
    planTitle: "CCTV 사각지대 점검",
    description: "설명",
    planDt: new Date("2025-08-07"),
  },
  {
    planSeq: 8,
    serviceTypeSeq: 32,
    serviceTypeName: "미화",
    planTitle: "층별 공용부 카펫 청소",
    description: "설명",
    planDt: new Date("2025-08-08"),
  },
  {
    planSeq: 9,
    serviceTypeSeq: 33,
    serviceTypeName: "설비",
    planTitle: "UPS 배터리 상태 점검",
    description: "설명",
    planDt: new Date("2025-08-09"),
  },
  {
    planSeq: 10,
    serviceTypeSeq: 31,
    serviceTypeName: "보안",
    planTitle: "비상 대피훈련 시나리오",
    description: "설명",
    planDt: new Date("2025-08-10"),
  },
  {
    planSeq: 11,
    serviceTypeSeq: 32,
    serviceTypeName: "미화",
    planTitle: "에스컬레이터 살균 청소",
    description: "설명",
    planDt: new Date("2025-08-11"),
  },
  {
    planSeq: 12,
    serviceTypeSeq: 33,
    serviceTypeName: "설비",
    planTitle: "보일러 연소상태 점검",
    description: "설명",
    planDt: new Date("2025-08-12"),
  },
  {
    planSeq: 13,
    serviceTypeSeq: 31,
    serviceTypeName: "보안",
    planTitle: "야간 출입기록 샘플링",
    description: "설명",
    planDt: new Date("2025-08-13"),
  },
  {
    planSeq: 14,
    serviceTypeSeq: 32,
    serviceTypeName: "미화",
    planTitle: "외벽 저층부 물걸레 청소",
    description: "설명",
    planDt: new Date("2025-08-14"),
  },
  {
    planSeq: 15,
    serviceTypeSeq: 33,
    serviceTypeName: "설비",
    planTitle: "공조기 필터 교체",
    description: "설명",
    planDt: new Date("2025-08-15"),
  },
  {
    planSeq: 16,
    serviceTypeSeq: 31,
    serviceTypeName: "보안",
    planTitle: "출입카드 분실현황 점검",
    description: "설명",
    planDt: new Date("2025-08-16"),
  },
  {
    planSeq: 17,
    serviceTypeSeq: 32,
    serviceTypeName: "미화",
    planTitle: "화장실 주기 소독",
    description: "설명",
    planDt: new Date("2025-08-17"),
  },
  {
    planSeq: 18,
    serviceTypeSeq: 33,
    serviceTypeName: "설비",
    planTitle: "소방펌프 주간 점검",
    description: "설명",
    planDt: new Date("2025-08-18"),
  },
];
